# Generated by Django 3.2.4 on 2021-07-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='phno',
            field=models.BigIntegerField(),
        ),
    ]
